In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [3]:
np.random.random((3,3,3))

array([[[0.23325788, 0.15345678, 0.44763208],
        [0.01983525, 0.57420416, 0.9099786 ],
        [0.18927832, 0.66095594, 0.9667938 ]],

       [[0.27678927, 0.56301793, 0.1790592 ],
        [0.17514191, 0.75258145, 0.17420577],
        [0.07575552, 0.37732744, 0.14157156]],

       [[0.18802621, 0.48382303, 0.59786631],
        [0.58079164, 0.81129194, 0.93750961],
        [0.20118383, 0.22703184, 0.96066885]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [11]:
b = np.random.random((5,5))
b = (b - np.mean(b)) / (np.std(b))
print(b)

[[-1.02990418  0.36172332  1.40490576  0.67143605 -1.19748056]
 [ 1.28229966 -0.80257091 -1.00694102 -0.22520841 -0.39935801]
 [ 1.33844221 -1.37317599  0.41917047  0.21808462  1.25170351]
 [ 1.05405305  0.51621343 -1.90260077  0.19938929  1.00227284]
 [ 0.95861991 -0.68734131 -0.35118459 -1.84236843  0.13982006]]


# 5.  How to find common values between two arrays?

In [13]:
c = np.random.randint(0,10,10)
d = np.random.randint(0,10,10)
print(np.intersect1d(c,d))

[1 4 5 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
print('yesterday =',np.datetime64('today') - np.timedelta64(1))
print('today =',np.datetime64('today'))
print('tomorrow =',np.datetime64('today') + - np.timedelta64(1))

yesterday = 2020-07-31
today = 2020-08-01
tomorrow = 2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [20]:
e = np.random.randint(0,2,10)
f = np.random.randint(0,2,10)

print(np.allclose(e,f))

print(np.array_equal(e,f))

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
a = np.random.random(15)
a[a.argmax()] = 0
print(a)

[0.47333022 0.22094699 0.59422986 0.75443808 0.         0.67180183
 0.55229508 0.25468206 0.35936304 0.53668016 0.22180152 0.90302565
 0.5425886  0.23188908 0.6015372 ]


# 9. How to print all the values of an array?

In [27]:
np.set_printoptions(threshold=float("inf"))
a = np.ones((20,20))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

# 10.Subtract the mean of each row of a matrix

In [29]:
a = np.random.rand(5,10)
print(a)
b = a - a.mean()

print(b)

[[0.00943409 0.81441451 0.13497502 0.96573914 0.2967262  0.32381046
  0.32750489 0.75056711 0.14664717 0.40373789]
 [0.42625442 0.17041826 0.75192143 0.24143191 0.79022012 0.90776025
  0.92178443 0.54929669 0.18151815 0.6990179 ]
 [0.06877897 0.93397639 0.06142174 0.71489545 0.18629474 0.94957714
  0.08804706 0.8850825  0.96976453 0.89945294]
 [0.74800535 0.62397484 0.39425192 0.71698597 0.79858414 0.79274736
  0.09899581 0.96307749 0.04711929 0.49583184]
 [0.76245634 0.33719927 0.11029991 0.32449106 0.8381822  0.99705232
  0.1675421  0.64437297 0.62510583 0.51576866]]
[[-0.52201623  0.28296419 -0.3964753   0.43428882 -0.23472413 -0.20763986
  -0.20394544  0.21911679 -0.38480315 -0.12771243]
 [-0.10519591 -0.36103207  0.2204711  -0.29001841  0.2587698   0.37630992
   0.39033411  0.01784637 -0.34993217  0.16756757]
 [-0.46267135  0.40252607 -0.47002859  0.18344513 -0.34515559  0.41812682
  -0.44340327  0.35363217  0.4383142   0.36800262]
 [ 0.21655503  0.09252452 -0.13719841  0.18553565

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [30]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 3. 4. 3. 4. 3. 2. 3. 3.]


In [31]:
np.add.at(Z, I, 1)
print(Z)

[5. 3. 5. 7. 5. 7. 5. 3. 5. 5.]


# 12.How to get the diagonal of a dot product?

In [32]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.61350345 0.56410871 0.67764848 0.48747254 0.62244798]
 [0.16121958 0.57785045 0.00758699 0.19475628 0.33743041]
 [0.35301512 0.02890922 0.57368011 0.89984212 0.42213325]
 [0.28025036 0.92963782 0.14736508 0.02798572 0.30725771]
 [0.34969255 0.35388542 0.80747591 0.28906528 0.06667358]]
[[0.71334192 0.64720492 0.95201583 0.76859949 0.14634237]
 [0.72635365 0.95169388 0.98635905 0.67909142 0.89017943]
 [0.08268511 0.66409222 0.49147683 0.61291212 0.96336093]
 [0.54546004 0.95823635 0.47836512 0.45216414 0.49201908]
 [0.52599688 0.20156842 0.51984759 0.11817469 0.92017171]]
diagonal of a dot product method 1 is.... [1.49671407 0.91395517 1.29643938 0.98599542 1.34766387]
diagonal of a dot product method 2 is.... [1.49671407 0.91395517 1.29643938 0.98599542 1.34766387]


# 13.How to find the most frequent value in an array?

In [33]:
a = np.random.randint(0,15,50)
print(a)
print(np.bincount(a).argmax())

[ 9  8  6 10  1  6  5  8 10  5 12  8  5  8 12 12 11  0 10 11  4 12  8 10
 10  1 10 11 12 10  0  1  0 11  4 11  1  6  2  7  2 10 10  5  7  2 10  6
  3  2]
10


# 14.How to get the n largest values of an array

In [35]:
a = np.arange(50000)
np.random.shuffle(a)
b = 10

print(a[np.argsort(a)[-b:]])

[49990 49991 49992 49993 49994 49995 49996 49997 49998 49999]


# 15.How to create a record array from a regular array?

In [36]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
